US618048: Updating copyright headers
CAFapi/util-flyway-installer pull request #7
Opened 2023-04-04 15:18 UTC by caoimhelynch

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=618048

2023-04-04 15:21 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=util-flyway-installer&BRANCH_NAME=US618048) to go ahead and create the build...

2023-04-04 15:25 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~util-flyway-installer~US618048~CI

2023-04-04 22:14 UTC, frankmccarry requested changes
Inception year has changed in this one.

2023-04-05 08:24 UTC, caoimhelynch commented
> Inception year has changed in this one.

I think this is correct as I did not change the inception year I just added it to the copyright notice. I think previously someone must have updated the copyright year without adding the inception year to copyright notice which is why it was 2022 in the header. However in the pom the inception year is 2021.

2023-04-05 08:38 UTC, frankmccarry approved these changes

2023-04-05 09:01 UTC, merged